name: build_web

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build_web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run clone
    - run: npm run unit
    - run: npm run webpack:build